autoload -U bashcompinit; bashcompinit
autoload -Uz compinit; compinit
# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html#cli-command-completion-linux
if (( $+commands[aws_completer] )); then
  complete -C aws_completer aws
fi
if [[ -f /etc/bash_completion.d/azure-cli ]]; then
  source /etc/bash_completion.d/azure-cli
fi
if [[ -f /usr/share/google-cloud-sdk/completion.zsh.inc ]]; then
  source /usr/share/google-cloud-sdk/completion.zsh.inc
fi
# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#configuring-argcomplete
# https://kislyuk.github.io/argcomplete/#zsh-support
if (( $+commands[register-python-argcomplete] )); then
  eval $(register-python-argcomplete ansible)
  eval $(register-python-argcomplete ansible-config)
  eval $(register-python-argcomplete ansible-console)
  eval $(register-python-argcomplete ansible-doc)
  eval $(register-python-argcomplete ansible-galaxy)
  eval $(register-python-argcomplete ansible-inventory)
  eval $(register-python-argcomplete ansible-playbook)
  eval $(register-python-argcomplete ansible-pull)
  eval $(register-python-argcomplete ansible-vault)
fi
# https://www.terraform.io/cli/commands#shell-tab-completion
if (( $+commands[terraform] )); then
  complete -C terraform terraform
fi
eval "$(starship init zsh)"
