name: publish-container-images

on:
  push:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pkgs
        timeout-minutes: 1
        run: |
          sudo apt-get install --assume-yes --no-install-recommends zsh
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      #
      # Login - ghcr.io
      - name: Login to ghcr.io
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}\
           | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
      #
      # Tag the image to the registry - ghcr.io
      - name: Generate tag prefix for ghcr.io
        run: |
          echo REGISTRY_PREFIX="ghcr.io/${{ github.repository_owner }}" >> $GITHUB_ENV
      #
      # Generate the tag
      - name: Generate the docker tag suffix using the git tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo TAG_SUFFIX="${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Generate the docker tag suffix using the current date
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo TAG_SUFFIX="$(date +%Y%m-)${GITHUB_SHA::7}" >> $GITHUB_ENV
      #
      # Build image
      # See also:
      #   - https://docs.docker.com/reference/cli/docker/buildx/build/#output
      #   - https://docs.docker.com/reference/cli/docker/buildx/build/#platform
      #   - https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
      # - name: Build the image
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   timeout-minutes: 60
      #   shell: zsh {0}
      #   run: |
      #     docker buildx build\
      #      --platform=linux/amd64,linux/arm64\
      #      --push\
      #      --tag=${REGISTRY_PREFIX}/provisioning:${TAG_SUFFIX}\
      #      Dockerfile.d/provisioning/
      # - name: Build the image
      #   if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      #   timeout-minutes: 60
      #   shell: zsh {0}
      #   run: |
      #     docker buildx build\
      #      --platform=linux/amd64,linux/arm64\
      #      --push\
      #      --tag=${REGISTRY_PREFIX}/provisioning:latest\
      #      Dockerfile.d/provisioning/
